build:
  image: fdplugins/android
  commands:
    - curl -o /usr/bin/framgia-ci https://raw.githubusercontent.com/framgia/ci-report-tool/master/dist/framgia-ci && chmod +x /usr/bin/framgia-ci
    - gradle :app:assembleDebug
    - framgia-ci run
