deploy:
  violationcomments:
    image: fdplugins/violation-comments:test
    enable: true
    createsinglefilecomments: true
    createCommentWithAllSingleFileComments: false
    commentOnlyChangedContent: true
    github:
      token: $$GITHUB_TOKEN
    violations:
       checkstyle: .*/reports/checkstyle/.*\\.xml$
deploy:
  violationcomments:
    image: fdplugins/violation-comments:echo
    enable: true
    createsinglefilecomments: true
    createCommentWithAllSingleFileComments: false
    commentOnlyChangedContent: true
    github:
      token: $$GITHUB_TOKEN
    violations:
      checkstyle: .*/reports/checkstyle/.*\\.xml$
notify:
  violationcomments:
    image: fdplugins/violation-comments
    enable: true
    createsinglefilecomments: true
    createCommentWithAllSingleFileComments: false
    commentOnlyChangedContent: true
    github:
      token: $$GITHUB_TOKEN
    violations:
       checkstyle: .*/reports/checkstyle/.*\\.xml$
  chatwork:
      image: fdplugins/chatwork
      room_id: 41136040
      token: $$CHATWORK_TOKEN
      format: "Test"