build:
  violationcomments:
    image: framgiaci/violation-comments
    environment:
      - ENABLE=true
      - CREATE_SINGLE_FILE_COMMENTS=true
      - CREATE_COMMENT_WITH_ALL_SINGLE_FILE_COMMENTS=false
      - COMMENT_ONLY_CHANGED_CONTENT=true
      - VIOLATION_CHECKSTYLE=.*/reports/checkstyle/checkstyle.xml$
    commands:
    - violationcomments