project_type: android
test:
  checkstyle:
    enable: true
    ignore: false
    command: gradle :app:checkstyle
  findbugs:
    enable: true
    ignore: true
    command: gradle :app:findbugs
  pmd:
    enable: true
    ignore: true
    command: gradle :app:pmd
  androidlint:
    enable: true
    ignore: true
    command: gradle :app:lintDebug

