project_type: android
test:
  checkstyle:
    command: gradle :app:checkstyle
  findbugs:
    ignore: true
    command: gradle :app:findbugs
  pmd:
    command: gradle :app:pmd
  androidlint:
    command: gradle :app:lintDebug

